name: GitHub Actions Demo 
on: [push]
jobs:
  Explore-Github-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Github Event Name $ {{github.event_name}}"
      - run: echo "System OS ${{runner.os}}"
      - run: echo "Branch Name ${{github.ref}}"
      - run: echo "Repo Name ${{github.repository}}"
      - name: Check out repository code
        uses: actions/checkout@v2ib
      - run: echo "Testing123"
      - name: List files in the repository
        run: |
          ls ${{github.workspace}}
      - ru: echo "This job's status is ${{job.status}}."